import pymysql
from sqlalchemy import INT, Column, Date, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Daily_Corona(Base):
    __tablename__ = "Daily_Corona"
    JCG_DT = Column(Date, nullable=False, primary_key=True)
    JONGNO = Column(INT, nullable=False)
    JONGNOADD = Column(INT, nullable=False)
    JUNGGU = Column(INT, nullable=False)
    JUNGGUADD = Column(INT, nullable=False)
    YONGSAN = Column(INT, nullable=False)
    YONGSANADD = Column(INT, nullable=False)
    SEONGDONG = Column(INT, nullable=False)
    SEONGDONGADD = Column(INT, nullable=False)
    GWANGJIN = Column(INT, nullable=False)
    GWANGJINADD = Column(INT, nullable=False)
    DDM = Column(INT, nullable=False)
    DDMADD = Column(INT, nullable=False)
    JUNGNANG = Column(INT, nullable=False)
    JUNGNANGADD = Column(INT, nullable=False)
    SEONGBUK = Column(INT, nullable=False)
    SEONGBUKADD = Column(INT, nullable=False)
    GANGBUK = Column(INT, nullable=False)
    GANGBUKADD = Column(INT, nullable=False)
    DOBONG = Column(INT, nullable=False)
    DOBONGADD = Column(INT, nullable=False)
    NOWON = Column(INT, nullable=False)
    NOWONADD = Column(INT, nullable=False)
    EP = Column(INT, nullable=False)
    EPADD = Column(INT, nullable=False)
    SDM = Column(INT, nullable=False)
    SDMADD = Column(INT, nullable=False)
    MAPO = Column(INT, nullable=False)
    MAPOADD = Column(INT, nullable=False)
    YANGCHEON = Column(INT, nullable=False)
    YANGCHEONADD = Column(INT, nullable=False)
    GANGSEO = Column(INT, nullable=False)
    GANGSEOADD = Column(INT, nullable=False)
    GURO = Column(INT, nullable=False)
    GUROADD = Column(INT, nullable=False)
    GEUMCHEON = Column(INT, nullable=False)
    GEUMCHEONADD = Column(INT, nullable=False)
    YDP = Column(INT, nullable=False)
    YDPADD = Column(INT, nullable=False)
    DONGJAK = Column(INT, nullable=False)
    DONGJAKADD = Column(INT, nullable=False)
    GWANAK = Column(INT, nullable=False)
    GWANAKADD = Column(INT, nullable=False)
    SEOCHO = Column(INT, nullable=False)
    SEOCHOADD = Column(INT, nullable=False)
    GANGNAM = Column(INT, nullable=False)
    GANGNAMADD = Column(INT, nullable=False)
    SONGPA = Column(INT, nullable=False)
    SONGPAADD = Column(INT, nullable=False)
    GANGDONG = Column(INT, nullable=False)
    GANGDONGADD = Column(INT, nullable=False)
    ETC = Column(INT, nullable=False)
    ETCADD = Column(INT, nullable=False)
